/**
 * NEW LIFE Sàrl - Données de Référence Portefeuille Participations & Filiales (Classe PCN 23)
 */

const DEFAULT_PARTECIPAZIONI = [
    {
        id: "PART-SAF",
        name: "Sombra e Agua Fresca Resort Sàrl",
        short_name: "Sombra e Agua Fresca Resort Sàrl",
        country: "Luxembourg (Filiale au Brésil)",
        country_code: "lu",
        flag: "🌴",
        legal_form: "Société à Responsabilité Limitée (Sàrl)",
        pcn_account: "233 - PARTICIPATIONS",
        pcn_code: "233",
        sector: "Hospitality & Luxury Resort (Praia de Pipa)",
        rcs_number: "RCS Luxembourg B228941",
        headquarters: "Luxembourg",
        rep_name: "Gérance & Direction",
        entry_date: "2020-01-28",
        initial_invested: 302245.51,
        divested_amount: 70520.00,
        vnc: 232725.00,
        pct_ownership: "25.00%",
        status: "active",
        status_label: "Actif (Cession Partielle 2024)",
        notes: "Società holding lussemburghese (Sàrl) con sede in Lussemburgo, controlla a sua volta la società operativa brasiliana Sombra Resort Brasil Sociedade Unipessoal Limitada con sede a Natal (Brasile), attiva nel settore dell'hospitality e resort di lusso a Praia de Pipa. Investimento storico di € 302.245,51 con cessione parziale di quote e 520 azioni a nov 2024 per € 70.520,00 (VNC a bilancio: € 232.725,00)."
    },
    {
        id: "PART-GEB",
        name: "Green Enerbras One SCSp",
        short_name: "Green Enerbras One SCSp",
        country: "Luxembourg (Projets Brésil)",
        country_code: "lu",
        flag: "🌱",
        legal_form: "Société en Commandite Spéciale (SCSp)",
        pcn_account: "2330 - GREEN ENERBRAS ONE SCSp",
        pcn_code: "2330",
        sector: "Investimenti Fotovoltaico a terra (Brasile)",
        rcs_number: "RCS Luxembourg (SCSp)",
        headquarters: "Luxembourg",
        rep_name: "NEW LIFE Sàrl (General Partner & Gérant Commandité)",
        entry_date: "2025-08-28",
        initial_invested: 1000.00,
        divested_amount: 0.00,
        vnc: 1000.00,
        pct_ownership: "Contrôle (General Partner)",
        status: "active",
        status_label: "Actif (Contrôle GP)",
        notes: "Società lussemburghese (SCSp) controllata e gestita da NEW LIFE Sàrl in qualità di General Partner. Attiva negli investimenti in impianti fotovoltaici a terra in Brasile. Ha acquisito la società operativa brasiliana TRI STAR ENERBRAS ONE SCP con sede a Natal (RN, Brasile)."
    },
    {
        id: "PART-SEF",
        name: "SEF Srl (Italie)",
        short_name: "SEF Srl",
        country: "Italie",
        country_code: "it",
        flag: "🇮🇹",
        legal_form: "Società a Responsabilità Limitata (S.r.l.)",
        pcn_account: "233 - PARTICIPATIONS",
        pcn_code: "233",
        sector: "Servizi alle Imprese & Attività Commerciali",
        rcs_number: "P.IVA / Cod. Fiscale IT-04892180261",
        headquarters: "Torino (Italia)",
        rep_name: "Tubia Edoardo / Amm. Unico",
        entry_date: "2026-09-07",
        initial_invested: 4000.00,
        divested_amount: 0.00,
        vnc: 4000.00,
        pct_ownership: "20.00%",
        status: "active",
        status_label: "Actif (Acquisition 09/2026)",
        notes: "Acquisition de participation finalisée le 07/09/2026 pour un montant de 4.000 € (solde d'achat), avec acte notarié et modification statutaire New Life (honoraires 1.800 €)."
    },
    {
        id: "PART-CREANCES",
        name: "Créances & Financement Associés (Compte PCN 234)",
        short_name: "Créances liées (234)",
        country: "Luxembourg",
        country_code: "lu",
        flag: "💶",
        legal_form: "Créance Financière",
        pcn_account: "234 - CRÉANCES / LIEN DE PARTICIPATION",
        pcn_code: "234",
        sector: "Financement Intra-Groupe & Associés",
        rcs_number: "Compte PCN 234",
        headquarters: "Luxembourg",
        rep_name: "Direction Financière",
        entry_date: "2022-01-12",
        initial_invested: 1496.67,
        divested_amount: 0.00,
        vnc: 1496.67,
        pct_ownership: "N/A",
        status: "active",
        status_label: "Actif",
        notes: "Créances diverses et avances de trésorerie rattachées aux participations et associés."
    }
];

const DEFAULT_PARTECIPAZIONI_DOCS = [
    {
        id: "DOC-SAF-01",
        part_id: "PART-SAF",
        part_name: "Sombra e Agua Fresca Resort Sàrl",
        title: "Statuts Constitutifs & Coordonnés Sombra e Agua Fresca Resort Sàrl (Luxembourg)",
        category: "statuts",
        date: "2018-10-15",
        filename: "Statuts_Sombra_e_Agua_Fresca_Resort_Sarl_Luxembourg.pdf",
        filepath: "docs/Statuts_Sombra_e_Agua_Fresca_Resort_Sarl_Luxembourg.pdf",
        size: "1.95 Mo",
        type: "PDF Document",
        notes: "Statuts coordonnés de la société holding luxembourgeoise immatriculée au RCS Luxembourg (B228941).",
        available: false
    },
    {
        id: "DOC-SAF-02",
        part_id: "PART-SAF",
        part_name: "Sombra e Agua Fresca Resort Sàrl",
        title: "Acte Notarié d'Acquisition de Parts Sociales Sombra e Agua Fresca Resort Sàrl",
        category: "acte",
        date: "2020-01-28",
        filename: "Acte_Acquisition_Parts_Sombra_Agua_Fresca_Sarl.pdf",
        filepath: "docs/Acte_Acquisition_Parts_Sombra_Agua_Fresca_Sarl.pdf",
        size: "2.45 Mo",
        type: "PDF Document",
        notes: "Protocole d'accord et acte d'acquisition des parts sociales de la société holding luxembourgeoise.",
        available: false
    },
    {
        id: "DOC-SAF-03",
        part_id: "PART-SAF",
        part_name: "Sombra e Agua Fresca Resort Sàrl",
        title: "Contrato Social & CNPJ - Sombra Resort Brasil Sociedade Unipessoal Ltda (Natal)",
        category: "statuts",
        date: "2020-03-10",
        filename: "Contrato_Social_Sombra_Resort_Brasil_Ltda_Natal.pdf",
        filepath: "docs/Contrato_Social_Sombra_Resort_Brasil_Ltda_Natal.pdf",
        size: "1.80 Mo",
        type: "PDF Document",
        notes: "Statuts d'immatriculation et inscription fiscale de la filiale opérationnelle brésilienne à Natal (Rio Grande do Norte), détenue par la Sàrl luxembourgeoise.",
        available: false
    },
    {
        id: "DOC-SAF-04",
        part_id: "PART-SAF",
        part_name: "Sombra e Agua Fresca Resort Sàrl",
        title: "Acte Notarié de Cession Partielle de Parts & 520 Actions (70.520 €)",
        category: "acte",
        date: "2024-11-28",
        filename: "Acte_Cession_Partielle_2024_SAF_Sarl.pdf",
        filepath: "docs/Acte_Cession_Partielle_2024_SAF_Sarl.pdf",
        size: "1.15 Mo",
        type: "PDF Document",
        notes: "Cession partielle de parts et 520 actions pour un montant encaissé de 70.000 € + 520 € sur compte POST New Life.",
        available: false
    },
    {
        id: "DOC-SAF-05",
        part_id: "PART-SAF",
        part_name: "Sombra e Agua Fresca Resort Sàrl",
        title: "Pacte d'Associés & Convention de Gouvernance SAF Resort Sàrl",
        category: "pacte",
        date: "2021-10-22",
        filename: "Pacte_Associes_Sombra_Agua_Fresca_Sarl.pdf",
        filepath: "docs/Pacte_Associes_Sombra_Agua_Fresca_Sarl.pdf",
        size: "890 Ko",
        type: "PDF Document",
        notes: "Règles de gouvernance, clause de préemption et répartition des droits sociaux entre associés.",
        available: false
    },
    {
        id: "DOC-SAF-06",
        part_id: "PART-SAF",
        part_name: "Sombra e Agua Fresca Resort Sàrl",
        title: "Bilan & Rapport Financier Annuel Sombra Resort Brasil & SAF Sàrl",
        category: "bilan",
        date: "2025-12-31",
        filename: "Bilan_SAF_Resort_Sarl_2025.pdf",
        filepath: "docs/Bilan_SAF_Resort_Sarl_2025.pdf",
        size: "3.10 Mo",
        type: "PDF Document",
        notes: "Comptes annuels de la holding luxembourgeoise et valorisation des actifs de la filiale hôtelière à Natal / Praia de Pipa.",
        available: false
    },
    {
        id: "DOC-GEB-01",
        part_id: "PART-GEB",
        part_name: "Green Enerbras One SCSp",
        title: "Contrat Social & Statuts Constitutifs Green Enerbras One SCSp (Luxembourg)",
        category: "statuts",
        date: "2025-08-20",
        filename: "Contrat_Social_Green_Enerbras_One_SCSp_Luxembourg.pdf",
        filepath: "docs/Contrat_Social_Green_Enerbras_One_SCSp_Luxembourg.pdf",
        size: "1.65 Mo",
        type: "PDF Document",
        notes: "Acte constitutif de la SCSp luxembourgeoise désignant New Life Sàrl comme Managing General Partner.",
        available: false
    },
    {
        id: "DOC-GEB-02",
        part_id: "PART-GEB",
        part_name: "Green Enerbras One SCSp",
        title: "Mandat General Partner & Governance Agreement (New Life Sàrl - GP)",
        category: "pacte",
        date: "2025-08-25",
        filename: "General_Partner_Agreement_New_Life_Green_Enerbras.pdf",
        filepath: "docs/General_Partner_Agreement_New_Life_Green_Enerbras.pdf",
        size: "820 Ko",
        type: "PDF Document",
        notes: "Convention de gérance et pouvoirs d'administration conférés à New Life Sàrl en tant qu'Associé Commandité.",
        available: false
    },
    {
        id: "DOC-GEB-03",
        part_id: "PART-GEB",
        part_name: "Green Enerbras One SCSp",
        title: "Contrat d'Acquisition de la SCP Brésilienne 'TRI STAR ENERBRAS ONE SCP' (Natal)",
        category: "acte",
        date: "2025-09-15",
        filename: "Acquisition_TRI_STAR_ENERBRAS_ONE_SCP_Natal.pdf",
        filepath: "docs/Acquisition_TRI_STAR_ENERBRAS_ONE_SCP_Natal.pdf",
        size: "2.10 Mo",
        type: "PDF Document",
        notes: "Contrat de cession et prise de participation dans la Sociedade em Conta de Participação (SCP) Tri Star Enerbras One SCP basée à Natal pour parcs solaires.",
        available: false
    },
    {
        id: "DOC-GEB-04",
        part_id: "PART-GEB",
        part_name: "Green Enerbras One SCSp",
        title: "Estatuto Social & Inscrição CNPJ - TRI STAR ENERBRAS ONE SCP (Natal - RN)",
        category: "visura",
        date: "2025-09-20",
        filename: "Estatuto_TRI_STAR_ENERBRAS_ONE_SCP_Natal.pdf",
        filepath: "docs/Estatuto_TRI_STAR_ENERBRAS_ONE_SCP_Natal.pdf",
        size: "1.35 Mo",
        type: "PDF Document",
        notes: "Statuts enregistrés et certificat fiscal de la SCP opérationnelle à Natal (Rio Grande do Norte, Brésil).",
        available: false
    },
    {
        id: "DOC-GEB-05",
        part_id: "PART-GEB",
        part_name: "Green Enerbras One SCSp",
        title: "Justificatif Bancaire de Virement Capital Contribution (1.000 €)",
        category: "quittance",
        date: "2025-08-28",
        filename: "Recu_Virement_Capital_Green_Enerbras_One.pdf",
        filepath: "docs/Recu_Virement_Capital_Green_Enerbras_One.pdf",
        size: "220 Ko",
        type: "PDF Document",
        notes: "Débit bancaire New Life compte POST du 28/08/2025 pour libération de la quote-part GP (1.000,00 €).",
        available: false
    },
    {
        id: "DOC-SEF-01",
        part_id: "PART-SEF",
        part_name: "SEF Srl (Italie)",
        title: "Atto Notarile di Cessione / Compravendita Quote Sociali SEF Srl",
        category: "acte",
        date: "2026-09-07",
        filename: "Atto_Notarile_Cessione_Quote_SEF_Srl.pdf",
        filepath: "docs/Atto_Notarile_Cessione_Quote_SEF_Srl.pdf",
        size: "1.95 Mo",
        type: "PDF Document",
        notes: "Atto di acquisto quote stipulato per il perfezionamento della partecipazione.",
        available: false
    },
    {
        id: "DOC-SEF-02",
        part_id: "PART-SEF",
        part_name: "SEF Srl (Italie)",
        title: "Visura Camerale Storica CCIAA Registro Imprese SEF Srl",
        category: "visura",
        date: "2026-09-28",
        filename: "SEF srl - visura del 28.9.26.pdf",
        filepath: "docs/SEF srl - visura del 28.9.26.pdf",
        size: "81.56 Ko",
        type: "PDF Document",
        notes: "Certificato di iscrizione alla Camera di Commercio con compagine sociale aggiornata al 28/09/2026.",
        available: true
    },
    {
        id: "DOC-SEF-03",
        part_id: "PART-SEF",
        part_name: "SEF Srl (Italie)",
        title: "Verbale Assemblea dei Soci & Modifiche Statutarie New Life Sàrl",
        category: "statuts",
        date: "2026-09-07",
        filename: "Verbale_Modifica_Statuti_New_Life_Acquisizione_SEF.pdf",
        filepath: "docs/Verbale_Modifica_Statuti_New_Life_Acquisizione_SEF.pdf",
        size: "720 Ko",
        type: "PDF Document",
        notes: "Delibera societaria New Life autorizzante l'operazione di investimento e modifica statuto.",
        available: false
    },
    {
        id: "DOC-SEF-04",
        part_id: "PART-SEF",
        part_name: "SEF Srl (Italie)",
        title: "Fattura Notarile & Ricevuta Pagamento Saldo Quota (4.000 €)",
        category: "quittance",
        date: "2026-09-07",
        filename: "Quietanza_Pagamento_Quota_SEF_Srl.pdf",
        filepath: "docs/Quietanza_Pagamento_Quota_SEF_Srl.pdf",
        size: "310 Ko",
        type: "PDF Document",
        notes: "Contabile bonifico POST New Life di 4.000 € e fattura onorari notarili di 1.800 €.",
        available: false
    },
    {
        id: "DOC-CRE-01",
        part_id: "PART-CREANCES",
        part_name: "Créances & Financement Associés (Compte PCN 234)",
        title: "Convention de Compte Courant d'Associé & Avances Financières",
        category: "financement",
        date: "2022-01-12",
        filename: "Convention_Avance_Compte_Courant_Associes.pdf",
        filepath: "docs/Convention_Avance_Compte_Courant_Associes.pdf",
        size: "540 Ko",
        type: "PDF Document",
        notes: "Convention régissant les avances et remboursements financiers associés et filiales.",
        available: false
    }
];

const HISTORICAL_PART_MOVEMENTS = [
    {
        date: "2020-01-28",
        entity: "Sombra e Agua Fresca Resort Sàrl",
        type: "Acquisition / Avance",
        compte: "233 - PARTICIPATIONS",
        description: "1er avance sur Achat Participation Sombra e Agua Fresca Resort Sàrl - Luxembourg",
        montant: -20000.00,
        direction: "SORTIE",
        doc_ref: "DOC-SAF-02"
    },
    {
        date: "2020-01-31",
        entity: "Sombra e Agua Fresca Resort Sàrl",
        type: "Acquisition / Avance",
        compte: "233 - PARTICIPATIONS",
        description: "2ème avance sur Achat Participation Sombra e Agua Fresca Resort Sàrl - Luxembourg",
        montant: -25000.00,
        direction: "SORTIE",
        doc_ref: "DOC-SAF-02"
    },
    {
        date: "2020-04-06",
        entity: "Sombra e Agua Fresca Resort Sàrl",
        type: "Acquisition / Avance",
        compte: "233 - PARTICIPATIONS",
        description: "1er avance complémentaire Sombra e Agua Fresca Resort Sàrl",
        montant: -20000.00,
        direction: "SORTIE",
        doc_ref: "DOC-SAF-02"
    },
    {
        date: "2020-04-14",
        entity: "Sombra e Agua Fresca Resort Sàrl",
        type: "Acquisition / Avance",
        compte: "233 - PARTICIPATIONS",
        description: "3ème avance sur Achat Participation Sombra e Agua Fresca Resort Sàrl",
        montant: -25000.00,
        direction: "SORTIE",
        doc_ref: "DOC-SAF-02"
    },
    {
        date: "2020-04-30",
        entity: "Sombra e Agua Fresca Resort Sàrl",
        type: "Acquisition / Avance",
        compte: "233 - PARTICIPATIONS",
        description: "2ème avance sur Achat Participation Sombra e Agua Fresca Resort Sàrl",
        montant: -40000.00,
        direction: "SORTIE",
        doc_ref: "DOC-SAF-02"
    },
    {
        date: "2020-06-30",
        entity: "Sombra e Agua Fresca Resort Sàrl",
        type: "Acquisition / Avance",
        compte: "233 - PARTICIPATIONS",
        description: "3ème avance sur Achat Participation Sombra e Agua Fresca Resort Sàrl",
        montant: -40000.00,
        direction: "SORTIE",
        doc_ref: "DOC-SAF-02"
    },
    {
        date: "2020-07-07",
        entity: "Sombra e Agua Fresca Resort Sàrl",
        type: "Acquisition / Avance",
        compte: "233 - PARTICIPATIONS",
        description: "4ème avance sur Achat Participation Sombra e Agua Fresca Resort Sàrl",
        montant: -25000.00,
        direction: "SORTIE",
        doc_ref: "DOC-SAF-02"
    },
    {
        date: "2020-09-30",
        entity: "Sombra e Agua Fresca Resort Sàrl",
        type: "Acquisition / Avance",
        compte: "233 - PARTICIPATIONS",
        description: "4ème avance complémentaire Sombra e Agua Fresca Resort Sàrl",
        montant: -40000.00,
        direction: "SORTIE",
        doc_ref: "DOC-SAF-02"
    },
    {
        date: "2020-10-14",
        entity: "Sombra e Agua Fresca Resort Sàrl",
        type: "Acquisition / Solde",
        compte: "233 - PARTICIPATIONS",
        description: "Solde Achat Participation Sombra e Agua Fresca Resort Sàrl - Luxembourg",
        montant: -25000.00,
        direction: "SORTIE",
        doc_ref: "DOC-SAF-02"
    },
    {
        date: "2020-12-21",
        entity: "Sombra e Agua Fresca Resort Sàrl",
        type: "Acquisition / Solde",
        compte: "233 - PARTICIPATIONS",
        description: "Solde final Achat Participation Sombra e Agua Fresca Resort Sàrl - Luxembourg",
        montant: -40000.00,
        direction: "SORTIE",
        doc_ref: "DOC-SAF-02"
    },
    {
        date: "2021-10-22",
        entity: "Sombra e Agua Fresca Resort Sàrl",
        type: "Capital Social",
        compte: "233 - PARTICIPATIONS",
        description: "Versement du Capital Social Sombra e Agua Fresca Resort Sàrl",
        montant: -2245.51,
        direction: "SORTIE",
        doc_ref: "DOC-SAF-05"
    },
    {
        date: "2022-01-12",
        entity: "Créances liées (234)",
        type: "Créances / Avance",
        compte: "234 - CRÉANCES / LIEN",
        description: "Financement Associés & Créances diverses rattachées",
        montant: -1496.16,
        direction: "SORTIE",
        doc_ref: "DOC-CRE-01"
    },
    {
        date: "2024-11-28",
        entity: "Sombra e Agua Fresca Resort Ltd / Sàrl",
        type: "Cession / Vente",
        compte: "233 - PARTICIPATIONS",
        description: "Vente Participation Sombra e Agua Fresca Resort Sàrl - Luxembourg",
        montant: 70000.00,
        direction: "ENTRÉE",
        doc_ref: "DOC-SAF-03"
    },
    {
        date: "2024-11-28",
        entity: "Sombra e Agua Fresca Resort Ltd / Sàrl",
        type: "Cession / Actions",
        compte: "233 - PARTICIPATIONS",
        description: "Vente d'actions (520 actions Sombra e Agua Fresca)",
        montant: 520.00,
        direction: "ENTRÉE",
        doc_ref: "DOC-SAF-03"
    },
    {
        date: "2025-08-28",
        entity: "Green Enerbras One SCSp",
        type: "Apport Capital GP",
        compte: "2330 - GREEN ENERBRAS ONE SCSp",
        description: "Versement de la Capital Contribution Green Enerbras One SCSp (General Partner)",
        montant: -1000.00,
        direction: "SORTIE",
        doc_ref: "DOC-GEB-05"
    },
    {
        date: "2026-09-07",
        entity: "SEF Srl (Italie)",
        type: "Acquisition",
        compte: "233 - PARTICIPATIONS",
        description: "Solde Achat Participation SEF Srl Italie",
        montant: -4000.00,
        direction: "SORTIE",
        doc_ref: "DOC-SEF-01"
    },
    {
        date: "2026-09-07",
        entity: "SEF Srl (Italie)",
        type: "Frais & Honoraires",
        compte: "613 - HONORAIRES",
        description: "Acte d'acquisition participation SEF Srl & Modifications Statuts New Life Sàrl",
        montant: -1800.00,
        direction: "SORTIE",
        doc_ref: "DOC-SEF-03"
    }
];

window.DEFAULT_PARTECIPAZIONI = DEFAULT_PARTECIPAZIONI;
window.DEFAULT_PARTECIPAZIONI_DOCS = DEFAULT_PARTECIPAZIONI_DOCS;
window.HISTORICAL_PART_MOVEMENTS = HISTORICAL_PART_MOVEMENTS;
